@startuml
package fr.shazilgerard.findmypatient.datamodel {
	class Patient{
		- String name
		- String address
		- Doctor
		- Room
		- UUID ID
		
		+ getName()
		+ get...()
		+ set...()
	}
	class User{
		- String name
		- String encryptedPassword
		- Rights rights
		
		+ getName()
		+ get()..
		+ set...()
	}
}
package fr.shazilgerard.findmypatient.view {
	class GUIView {
		GUIView(IdentityController controller)
	 	{static} void main()
	}
}
package fr.shazilgerard.findmypatient.controller {
	class IdentityController{
		- IDAOManagement patientDaoManagement
		- IDAOManagement userDaoManagement
		- User currentUser
		- UserManagement userManagement
		- Settings settings
		
		+ IdentityController()
		+ getCurrentUserName()
		+ UserManagement getUserManagement()
		+ PatientMangement getPatientManagement()
		+ login(String name, String password)
		+ logout()
	}
	class UserManagement{
		- IDataDAO<User> userDao
		
		+ UserManagement(IDataDAO<User> userDao)
		+ User validate(user, password)
		+ add(User user)
		+ delete(User user)
		+ modify(User user)
		+ getRights(User user)
	}
	class PatientManagement{
		- UserManagement userManagement
		- IDataDAO<Patient> patientDao
		
		+ PatientMangament(UserManagement userManagement, 
		   IDataDAO<Patient> patientDao)
		+ add(Patient patient)
		+ delete(Patient patient)
		+ modify(Patient patient)
		+ getAll()
	}
}

package fr.shazilgerard.findmypatient.config {
	class Settings {
		- final long serialVersionUID = 0L
		- String DataBaseName
		- String DataBaseEncryptedPass
		- Etc..
		
		+ getAndSet()
	}
	class Configuration {
		+ void read()
		+ void save()
		+ Settings get()
	}
	Settings -() Serializable 
	Configuration *- Settings
}

package fr.shazilgerard.findmypatient.dao {
	interface IDataDAO<DataType>{
		+ List<DataType> get(IMatcher<DataType> matcher)
		+ DataType getAll(void)
		+ modify(DataType data)
		+ delete(DataType data)
	}
	interface IDAOManagement{
		+ createDAO()
		+ deleteDAO()
	}
	class DAOCreator{
	}
	class JDBCDAO<DataType> <<abstract>>{
		+ JDBCDAO()
		+ createDAO()
		+ deleteDAO()
		..
		+ List<DataType> get(IMatcher<DataType> matcher)
		+ DataType getAll(void)
		+ modify(DataType data)
		+ delete(DataType data)
		..
		# {abstract} readDataFields()
		# {abstract} writeDataFields()
	}
	class UserJDBCDAO{
		+ UserJDBCDAO(String DBinfo..)
		# readDataFields()
		# writeDataFields()
	}
	class PatientJDBCDAO{
		+ PatientJDBCDAO(String DBinfo..)
		# readDataFields()
		# writeDataFields()
	}
}
package fr.shazilgerard.findmypatient.helper {

	interface IMatcher<T>{
		match()
	}
	class NameMatcher --|> IMatcher
	class IDMatcher --|> IMatcher
}
package fr.shazilgerard.findmypatient.exceptions {
	class SomeFunctionalExceptions
}

IdentityController *-- UserManagement
IdentityController *-- PatientManagement
Settings -* IdentityController
UserManagement -* PatientManagement
	
GUIView *-- IdentityController

UserManagement --> User
PatientManagement --> Patient

	
UserJDBCDAO --|> JDBCDAO
PatientJDBCDAO --|> JDBCDAO
JDBCDAO --|> IDataDAO
JDBCDAO --|> IDAOManagement

@enduml