@startuml

package fr.shazilgerard.findmypatient.view {
	class GUIView
}
package fr.shazilgerard.findmypatient.controller {
	class IdentityController
}
package fr.shazilgerard.findmypatient.datamodel {
	class User
	class Patient
	
	class UserManagement
	class PatientManagement
	class UserAuthority
}

package fr.shazilgerard.findmypatient.dao {
	class IDataDAO  
	class IDAOManagement
	class JDBCDAO
	class UserJDBCDAO
	class PatientJDBCDAO 
}

IDataDAO <|.. JDBCDAO  
IDAOManagement <|.. JDBCDAO
JDBCDAO <|-- UserJDBCDAO
JDBCDAO <|-- PatientJDBCDAO 

IdentityController "1" o-- UserManagement
IdentityController "1" o-- PatientManagement
IdentityController "1" o-- UserAuthority

UserManagement --> User
PatientManagement --> Patient
	
GUIView o-- IdentityController

@enduml