CREATE TABLE USERS
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	RIGHTS VARCHAR(255)
);
INSERT INTO USERS(NAME,PASSWORD,RIGHTS) VALUES('admin','admin','ReadWriteAndUserManagement');
