CREATE TABLE PATIENTS
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255),
	ROOM VARCHAR(255)
)

CREATE TABLE USERS
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255),
	PASSWORD VARCHAR(255)
)